AddCSLuaFile("shared.lua")
AddCSLuaFile("config.lua")
include("shared.lua")
include("config.lua")
AddCSLuaFile("lang/cl_english.lua")
include("lang/cl_english.lua")
Logger("Disabling motd message")
game.ConsoleCommand("ulx_motddisabledmessage 1\n")